spring:
  application:
    name: cim-async

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver:
      class: oracle.jdbc.driver.OracleDriver
    username: objtransfer
    password: password
  jpa:
    show-sql: true

server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    