spring:
  application:
    name: cii
      
  cloud:
    stream:
      bindings:
        output:
          destination:  metricQueue
          content-type: application/json
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
            