spring:
  application:
    name: cii
    
  cloud:
    stream:
      bindings:
        output:
          destination:  metricQueue
          content-type: application/json
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
            