-- login as imadmin
GRANT SELECT, INSERT, UPDATE, DELETE ON imadmin.IM_TRANSACTION_SUMMARIES TO imwriter;
GRANT SELECT, INSERT, UPDATE, DELETE ON imadmin.IM_COMMAND_SUMMARIES TO imwriter;
GRANT SELECT, INSERT, UPDATE, DELETE ON imadmin.IM_SERVICE_REQUEST_SUMMARIES TO imwriter;
GRANT SELECT, INSERT, UPDATE, DELETE ON imadmin.IM_TRANSACTION TO imwriter;
GRANT SELECT ON imadmin.IM_SEQ TO imwriter;

-- login as imwriter
CREATE SYNONYM im_transaction_summaries FOR imadmin.IM_TRANSACTION_SUMMARIES;
CREATE SYNONYM im_command_summaries FOR imadmin.IM_COMMAND_SUMMARIES;
CREATE SYNONYM im_service_request_summaries FOR imadmin.IM_SERVICE_REQUEST_SUMMARIES;
CREATE SYNONYM im_transaction FOR imadmin.IM_TRANSACTION;
CREATE SYNONYM im_seq FOR imadmin.IM_SEQ;

